CREATE TABLE app_lispb (
                       id INT(7) NOT NULL AUTO_INCREMENT PRIMARY KEY,
                       program VARCHAR(40) NOT NULL,
                       piano VARCHAR(4) NOT NULL,
                       violin INT(4) NULL,
                           alt INT(4) NULL,
                           violoncello INT(4) NULL,
                           doublebass INT(4) NULL,
                           harp INT(4) NULL,
                           flute INT(4) NULL,
                           oboe INT(4) NULL,
                           clarinet INT(4) NULL,
                           trumpet INT(4) NULL,
                           tenor INT(4) NULL,
                           trombone INT(4) NULL,
                           frenchhorn INT(4) NULL,
                           tuba INT(4) NULL,
                           drum INT(4) NULL,
                           bayan INT(4) NULL,
                           accordion INT(4) NULL,
                           domra INT(4) NULL,
                           balalaika INT(4) NULL,
                           psaltery INT(4) NULL,
                           guitar INT(4) NULL,
                           saxophone INT(4) NULL,
                           trombone_2 INT(4) NULL,
                           drum_2 INT(4) NULL,
                           guitar_2 INT(4) NULL,
                           guitar_3 INT(4) NULL,
                           chorus INT(4) NULL,
                           folklore INT(4) NULL,
                           from_lastname VARCHAR(100) NULL,
                           from_name VARCHAR(100) NULL,
                           from_patronymic VARCHAR(100) NULL,
                           from_non_patronymic BOOLEAN NOT NULL DEFAULT false,
                           from_lastname_child VARCHAR(100) NULL,
                           from_name_child VARCHAR(100) NULL,
                           from_patronymic_child VARCHAR(100) NULL,
                           non_patronymic_child BOOLEAN NOT NULL DEFAULT false,
                           sopd BOOLEAN NOT NULL DEFAULT false,
                           sopdch BOOLEAN NOT NULL DEFAULT false,
                           uuli BOOLEAN NOT NULL DEFAULT false,
                           ppu BOOLEAN NOT NULL DEFAULT false,
                           pppoo BOOLEAN NOT NULL DEFAULT false,
                           ppr BOOLEAN NOT NULL DEFAULT false,
                           pio BOOLEAN NOT NULL DEFAULT false,
                           lastname_child VARCHAR(100) NULL,
                           name_child VARCHAR(100) NULL,
                           patronymic_child VARCHAR(100) NULL,
                           non_patronymic_child_2 BOOLEAN NOT NULL DEFAULT false,
                           date_of_birth DATE NULL,
                           age_month INT(2) NULL,
                        age_years INT(2) NULL,
                           index_zip INT(6) NULL,
                           city VARCHAR(100) NULL,
                           street VARCHAR(100) NULL,
                           number_house INT(10) NULL,
                           building VARCHAR(10) NULL,
                           apartment INT(10) NULL,
                           school VARCHAR(300) NULL,
                           shift INT(1) NULL,
                           mi_01 BOOLEAN NOT NULL DEFAULT false,
                           musical_instrument VARCHAR(100) NULL,
                           student_01 BOOLEAN NOT NULL DEFAULT false,
                           student VARCHAR(100) NULL,
                           department VARCHAR(100) NULL,
                           teacher VARCHAR(100) NULL,
                           benefits_01 BOOLEAN NOT NULL DEFAULT false,
                           benefits VARCHAR(100) NULL,
                           special_conditions_01 BOOLEAN NOT NULL DEFAULT false,
                           special_conditions VARCHAR(100) NULL,
                           single_parent BOOLEAN NOT NULL DEFAULT false,
                           degree_of_kinship VARCHAR(25) NULL,
                           lastname_1 VARCHAR(100) NULL,
                           name_1 VARCHAR(100) NULL,
                           patronymic_1 VARCHAR(100) NULL,
                           non_patronymic_1 BOOLEAN NOT NULL DEFAULT false,
                           address_same_1 BOOLEAN NOT NULL DEFAULT false,
                           index_zip_1 INT(6) NULL,
                           city_1 VARCHAR(100) NULL,
                           street_1 VARCHAR(100) NULL,
                           number_1 INT(10) NULL,
                           building_1 VARCHAR(10) NULL,
                           apartment_1 INT(10) NULL,
                           place_work_1 VARCHAR(200) NULL,
                           post_1 VARCHAR(200) NULL,
                           phone_1 INT(10) NULL,
                           email_1 VARCHAR(100) NULL,
                           lastname_2 VARCHAR(100) NULL,
                           name_2 VARCHAR(100) NULL,
                           patronymic_2 VARCHAR(100) NULL,
                           non_patronymic_2 BOOLEAN NOT NULL DEFAULT false,
                           address_same_2 BOOLEAN NOT NULL DEFAULT false,
                           index_zip_2 INT(6) NULL,
                           city_2 VARCHAR(100) NULL,
                           street_2 VARCHAR(100) NULL,
                           number_2 INT(10) NULL,
                           building_2 VARCHAR(10) NULL,
                           apartment_2 INT(10) NULL,
                           place_work_2 VARCHAR(200) NULL,
                           post_2 VARCHAR(200) NULL,
                           phone_2 INT(10) NULL,
                           email_2 VARCHAR(100) NULL,
                           passport_1 BLOB NULL,
                           passport_2 BLOB NULL,
                           birth_certificate BLOB NULL,
                           consent_email BOOLEAN NOT NULL DEFAULT false,
                           consent_telegram BOOLEAN NOT NULL DEFAULT false,
                           consent_non BOOLEAN NOT NULL DEFAULT true
);
